version: "3"
services:
  web:
    build:
      context: ./

    depends_on:
      - postgres
      - redis
    ports:
      - '8000:8000'
    environment:
      DEBUG: 'true'
      DATABASE_URL: 'psql://dev:dev@postgres:5432/todoapp'
      REDIS_URL: 'redis://redis:6379/1'
      THP_GOOGLE_OAUTH2_CLIENT_ID: ''
      THP_GOOGLE_OAUTH2_CLIENT_SECRET: ''
      THP_GOOGLE_OAUTH2_PROJECT_ID: ''
      THP_LINKEDIN_CLIENT_ID: ''
      THP_LINKEDIN_CLIENT_SECRET: ''
      CHANNEL_REDIS: (127.0.0.1, 6379)
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: todoapp
      POSTGRES_USER: dev

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
