from .base import env

GOOGLE_OAUTH2_CLIENT_ID = env.str("THP_GOOGLE_OAUTH2_CLIENT_ID", default="")
GOOGLE_OAUTH2_CLIENT_SECRET = env.str("THP_GOOGLE_OAUTH2_CLIENT_SECRET", default="")
GOOGLE_OAUTH2_PROJECT_ID = env.str("THP_GOOGLE_OAUTH2_PROJECT_ID", default="")

LINKEDIN_CLIENT_ID = env.str("THP_LINKEDIN_CLIENT_ID", default="")
LINKEDIN_CLIENT_SECRET = env.str("THP_LINKEDIN_CLIENT_SECRET", default="")
# LINKEDIN_SOCIAL_SECRET = env.str("THP_LINKEDIN_SOCIAL_SECRET", default="")
# LINKEDIN_REDIRECT_URL = env.str("THP_LINKEDIN_REDIRECT_URL", default="")
